export const data = {
  products: [
    {
      id: '1',
      name: 'underground  ring',
      image: '/images/gold1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality ring',
    },
    {
        id: '2',
        name: 'Pardis bangle',
        image: '/images/gold2.jpg',
        price: 215,
        countInStock: 3,
        rating: 5,
        numReviews: 8,
        description: 'only size 1,2',
      },
      {
        id: '3',
        name:'Ring bracelet',
        image: '/images/gold3.jpg',
        price: 180,
        countInStock: 2,
        rating: 3.5,
        numReviews: 11,
        description: 'high quality ring',
      },
      {
        id: '4',
        name: 'bracelet',
        image: '/images/gold4.jpg',
        price: 135,
        countInStock: 5,
        rating: 4,
        numReviews: 4,
        description: 'very subtle',
      },
  ],
}
